### ISSUE TITLE
Where can I find the .apk of this application?

### ISSUE THREAD

**Issue by parthgupta0912** [deib-polimi/PigeonMessanger#1]
Cannot import this project to Android studio.It contains errors.
Also cannot find .apk of this application.

**Comment by Ks89** [comment]
The project is ok. Look the screenshot. I imported the project right now and executed it.
Can you explain in detail the error?

The apk is available here: https://github.com/Ks89/PigeonMessenger/releases/tag/v.alpha-2
I'm sorry, I forgot to update also this repository.

![senza titolo](https://cloud.githubusercontent.com/assets/6057207/11763595/51e5ba2e-a111-11e5-9c85-069c258342c7.png)

**Comment by Ks89** [comment]
Apk published here https://github.com/deib-polimi/PigeonMessanger/releases/tag/v.alpha-2.1

PS: to be able to compile you must install the Project Lombok plugin in Android Studio.
