### ISSUE TITLE
app not working help

### ISSUE THREAD

**Issue by Okezie** [deib-polimi/PigeonMessanger#3]
Please the app is not working at all

**Comment by Ks89** [comment]
Hi.
What it means that it is not working?

Please give me all necessary information. Device, OS version and so on...

Also, please send me a log message or something like that.

**Comment by Okezie** [comment]
It doesn't discover other devices I have turned on Wi-Fi direct on my phone but still can't discover other phones, what do I do please.

**Comment by Ks89** [comment]
Did you see logcat with Android studio + debug mode enabled if there is an error?

Also, which device are you using and which android version?

**Comment by Okezie** [comment]
Itel 1516 plus Android 5.1
Just tested with my phone
Will send my log report as soon as I power my pc

**Comment by Ks89** [comment]
I never heard this device, but probably the problem itself is related to your device.
Wi-FI Direct is a terrible protocol also with the best driver and on really expensive devices.
For example, I developed this app with a Nexus 5, but trying the same app with a Samsung Galaxy S4 LTE (really more expensive), I saw more and more problems.

So, the best thing that you can do is to try this app with another device. Sometimes, customers change device software. For example, Samsung modified the behavour of wpa_supplicant, the low level software written in C, used by the Android Framework to communicate with the wifi driver (most of the time, not open source).

**Comment by Okezie** [comment]
Thanks alot for your concern I guess that must be the problem, I am still struggling from my end. I just have to deliver this project.  Thanks for your concern once more.
