### ISSUE TITLE
Help to Understand the Code

### ISSUE THREAD

**Issue by maryamhashemi** [deib-polimi/PigeonMessanger#4]
Hi. I downloaded your project and run it. that was perfect. But I would like to implement something like this. I don't understand your project's code completely. Is there any resource that I can use to implement an application like this?

I tried and I've just been able to do this <https://github.com/maryamhashemi/WiFiDirect>.

**Comment by Ks89** [comment]
I'm sorry but I cannot give support on this project. Its very old and abandoned. Also it was a small example created for my master thesis. Feel free to experiment by yourself.
